### ISSUE TITLE
Поправка

### ISSUE THREAD

**Issue by Kvitdrake** [MaksBerkutov/MagazineTelegramBot#1]
Чувак, привет. Советую тебе стереть из публичного репо реальный токен, его могут использовать для своих проектов и уничтожить твою работу. Если это лже-токен - ок, если нет (очень просто похож) - советую стереть. Удачи!

**Comment by MaksBerkutov** [comment]
Привет, да токен не валидный не парься. 
Но спасибо за беспокойствто)

**Comment by MaksBerkutov** [comment]
> Чувак, привет. Советую тебе стереть из публичного репо реальный токен, его могут использовать для своих проектов и уничтожить твою работу. Если это лже-токен - ок, если нет (очень просто похож) - советую стереть. Удачи!

Привет, да токен не валидный не парься.
Но спасибо за беспокойствто)
